### ISSUE TITLE
`dit new` not reading input from command line call

### ISSUE THREAD

**Issue by jzsampaio** [filipelbc/dit#200]
If I run `dit new "foo" `, the program asks me for the title of the task. I expected "foo" to be recognized as the name of the task.

**Comment by jzsampaio** [comment]
I've tried adding a task name + title and still didn't get it to work:

```
dit new review_3 "Review MR 3"
ERROR: Unrecognized argument: Review MR 3
```

**Comment by filipelbc** [comment]
You actually need to do `dit new foo -: "Review MR 3"`

But indeed requiring the `-:` token is unnecessary and counter intuitive. It should be removed.
