### ISSUE TITLE
Improve exceptions and error handling mechanism

### ISSUE THREAD

**Issue by danielmoraes** [filipelbc/dit#38]
Guidelines for error handling:
- Avoid using exceptions if error can be detected and avoided
- Use exceptions if it is not possible to recover from error (program should stop and exit)
- Use exceptions if it would make code simpler (leaving deep loops or deep function call stack)

Items to be examined:
- Have proper custom exceptions with meaningful names
- Catch common python exceptions

Use good judgement to decide how to handle error:
- Aim for simplicity and clarity of code

**Comment by filipelbc** [comment]
Also catch some python exceptions, for instance, when a `pop(0)` happens on an empty `argv`
