### ISSUE TITLE
Syntax of list/export commands

### ISSUE THREAD

**Issue by danielmoraes** [filipelbc/dit#40]
The syntax of the list/export commands are a little bit confusing. Especially the "." to denote the root group, since "." is usually used to denote the current place, not the top level one.

One idea: always use the full path of a group, subgroup, or task (group/subgroup/task), except for the following alias:
1. "./" or "." to refer to the current subgroup (e.g., `"dit list ./a"` lists the task "a" of the current subgroup and `"dit list ./"` or `"dit list ."` lists the current subgroup);
2. "../" or ".." to refer to the current group (e.g., `"dit list ../a"` lists the task "a" of the current group and `"dit list .."` or `"dit list ../"` lists the current group).

Note that in this way the commands `dit list a` ot `dit new a` will refer to the task "a" on the "" group/subgroup, not the current group/subgroup.

**Comment by filipelbc** [comment]
Right now, besides accepting empty string (`""`) as the "root" (sub)group, it also accepts `"."`.

Another thing: `new` and `list` have different arguments, `<name>` and `<gname>` respectively, since it makes little sense to prioritize **tasks** instead of **groups** in `list`

**Comment by filipelbc** [comment]
WONTFIX. At least for now.
