### ISSUE TITLE
There need be more clarification on the behavior of the `status` command.

### ISSUE THREAD

**Issue by danielmoraes** [filipelbc/dit#58]
`dit status` seems to be listing all tasks from the current group/subgroup when there are no running tasks (started but not concluded).

**Comment by filipelbc** [comment]
That is the expected behavior. What is the problem?

**Comment by danielmoraes** [comment]
Can you explain the behavior of `dit status` for you? For me, it should list "current working tasks", that is, tasks that have been "started" (and maybe paused) but not "completed". Technically, not concluded tasks that have something in the logbook entry.

**Comment by filipelbc** [comment]
Closing this and opening #94.
