### ISSUE TITLE
Remove --id prefix

### ISSUE THREAD

**Issue by danielmoraes** [filipelbc/dit#65]
The ID of tasks and groups is always an integer. The "name" of tasks always starts with an alphanumeric character. Based on this, the --id prefix can be suppressed with a simple checking on the first character of the input string.

Note that, with this update, it will not be possible anymore to refer to the root group or to the root subgroup of an "id" or "gid" with the empty string. Instead, one must use the integer "0". For instance, ""/0/0 is invalid.

**Comment by filipelbc** [comment]
> Note that, with this update, it will not be possible anymore to refer to the root group or to the root subgroup of an "id" or "gid" with the empty string. Instead, one must use the integer "0". For instance, ""/0/0 is invalid.

Avoid this. Also check for "/" or ".".
